apiVersion: batch/v1
kind: Job
metadata:
  name: redis-data-transfer-job
spec:
  template:
    spec:
      containers:
      - name: redis-data-transfer
        image: <your-docker-image>
        args:
        - "-old=<OLD_REDIS_URL>"
        - "-new=<NEW_REDIS_URL>"
      restartPolicy: Never
  backoffLimit: 1
